-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 07 Nov 2024 pada 07.46
-- Versi server: 10.4.32-MariaDB
-- Versi PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `toko_buku`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `buku`
--

CREATE TABLE `buku` (
  `id` int(11) NOT NULL,
  `isbn` varchar(16) NOT NULL,
  `judul` varchar(255) NOT NULL,
  `penulis` varchar(100) NOT NULL,
  `penerbit` varchar(100) NOT NULL,
  `deskripsi` longtext NOT NULL,
  `harga` decimal(10,0) NOT NULL,
  `cover` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `buku`
--

INSERT INTO `buku` (`id`, `isbn`, `judul`, `penulis`, `penerbit`, `deskripsi`, `harga`, `cover`) VALUES
(1, '9786230302176', 'Three Days Of Happiness', 'Miaki Sugaru', 'm&c!', 'Sipnosis\r\n“Kalian pasti tahu kalau hidup manusia tak ternilai dan tak bisa ditukar dengan apa pun. Nah, sekarang coba bayangkan, jika hidup manusia bisa dihitung dengan uang, menurut kalian berapa nilainya?” Kusunoki betul-betul sudah menyerah dengan hidupnya. Tak punya uang, tak punya teman, tak punya mimpi, dan tak ada hal spektakuler yang terjadi seperti janjinya pada Himeno—perempuan spesial dalam hidupnya—sepuluh tahun lalu. Di saat seperti itu, dia mendengar mengenai sebuah toko yang bisa membeli sisa hidup. Toko tersebut membuatnya bertemu dengan Miyagi, seorang pengawas misterius penuh rahasia yang dikirimkan untuk mengawasi sisa hidupnya… Akankah pertemuannya dengan Miyagi membuat sisa hidupnya menjadi lebih bermakna dibandingkan 20 tahun hidup yang sudah dilaluinya?\r\n\r\n“Sama seperti judulnya. Ini adalah bacaan singkat tapi sangat berkesan bagiku. Kamu akan benar-benar terikat dengan karakter dan tema di keseluruhan novel dan itu sangat menarik. Tema terkait menjual perjalanan kehidupanmu itu sangat menarik, tetapi cerita utamanya berfokus pada \"apa yang akan kamu lakukan dengan waktu yang tersisa?\" Ngomong-ngomong, saya tidak bisa untuk tidak memberikan rekomendasi terkait novel ini untuk dibaca. Cerita dalam novel ini sangat bagus dan saya harap kami mendapatkan lebih banyak terjemahan dari novel ringan sejenis untuk waktu segera,” Jesus Salas, Pembaca.\r\n\r\n“Biasanya saya tidak terlalu suka genre percintaan, tapi Three Days of Happiness punya plot yang jauh lebih dalam. Novel ini dapat memberitahumu arti dari hidup dan bagaimana kamu harus menghargainya. Bukunya juga sedih banget,” Evan Yang, Pembaca.\r\n\r\nDetail Produk:\r\nPenulis: Sugaru Miaki\r\nPenerbit: M&C!\r\nISBN: 9786230302176\r\nEditor: Shafira Amanita\r\nTerbit: 13 Juli 2020\r\nHalaman: 256 Halamam\r\nLebar: 13 cm\r\nBerat: 0.18 kg', 60000, 'ThreeDaysOfHappiness.jpg'),
(2, '9786230302589', 'I Sold My Life For Ten Thousand Yen Per Year', 'Miaki Sugaru', 'm&c!', 'Komik I Sold My Life For Ten Thousand Yen Per Year 02 Of 03\r\n\r\nDisclaimer\r\nCerita dalam komik ini mengandung adegan yang diperuntukan untuk pembaca dewasa. Tidak dianjurkan untuk dibaca anak-anak di bawah umur.\r\n\r\nThree Days of Happiness (Mikkakan no kōfuku) merupakan novel yang ditulis oleh Sugaru Miaki dan diilustrasikan oleh Shōichi Taguchi dan diterbitkan pertama pada 25 Desember 2013. Novel ini kemudian diadaptasi menjadi manga berjudul “I Sold My Life For Ten Thousand Yen Per Year” yang diterbitkan pada aplikasi Shōnen Jump+ kemudian dikumpulkan dan di-print volumenya. I Sold My Life For Ten Thousand Yen Per Year mengisahkan tentang Kusunoki yang harus berjuang mendapatkan makanan karena kemiskinan yang melanda dirinya. Pemilik toko tua yang kasihan melihat Kusunoki pun menyarankan Kusunoki untuk pergi ke toko yang konon katanya dapat membeli umur, waktu, dan kesehatan. Kusunoki pun mengikuti saran pemilik toko itu. Ia hancur saat mengetahui nilai uang yang akan didapatnya dari menjual umurnya. Ia memutuskan untuk menjual 30 tahun hidupnya seharga sepuluh ribu yen per tahun. Ia pun akhirnya pulang dan bertemu petugas toko yang tadi ia datangi, petugas itu bernama Miyagi. Miyagi ditugaskan untuk mengamati hidup Kusunoki sampai tiga hari terakhir hidup Kusunoki.\r\n\r\n\r\nKusunoki membuat daftar hal-hal yang ingin dia lakukan sebelum mati.\r\nSekarang dia hanya punya waktu 3 bulan untuk mewujudkannya. Salah satunya adalah bertemu Himeno, gadis yang selama 10 tahun ini dia rindukan.\r\nBerbekal alamat di surat dia mendatangi ruman Himeno.\r\nSanggupkah Kusunoki mewujudkan harapannya?\r\n\r\nKelanjutan dari I Sold My Life For Ten Thousand Yen Per Year 01\r\nJudul: Komik I Sold My Life For Ten Thousand Yen Per Year 02 Of 03\r\nRating: yang diperuntukan untuk pembaca dewasa.\r\nCerita & Ilustrasi: MIAKI SUGARU / TAGUCHI SHOUICHI\r\nTebal: 200 halaman\r\nFormat: Soft Cover\r\nTanggal Terbit: 25 Nov 2020\r\nISBN : 9786230302589\r\nBerat : 0.1 kg\r\nDimensi : 17.2 cm x 11.4 cm', 30000, 'ISoldMyLifeForTenThousandYenPerYear.jpg'),
(8, '9786024285883', 'Atomic Habits', 'James Clear', 'Penguin Uk', 'People think that when you want to change your life, you need to think big. But world-renowned habits expert James Clear has discovered another way. He knows that real change comes from the compound effect of hundreds of small decisions: doing two push-ups a day, waking up five minutes early, or holding a single short phone call.\r\n\r\nHe calls them atomic habits.\r\n\r\nIn this ground-breaking book, Clears reveals exactly how these minuscule changes can grow into such life-altering outcomes. He uncovers a handful of simple life hacks (the forgotten art of Habit Stacking, the unexpected power of the Two Minute Rule, or the trick to entering the Goldilocks Zone), and delves into cutting-edge psychology and neuroscience to explain why they matter. Along the way, he tells inspiring stories of Olympic gold medalists, leading CEOs, and distinguished scientists who have used the science of tiny habits to stay productive, motivated, and happy.\r\n\r\nThese small changes will have a revolutionary effect on your career, your relationships, and your life.\r\n________________________________\r\nA NEW YORK TIMES AND SUNDAY TIMES BESTSELLER\r\n\r\n\'A supremely practical and useful book.\' Mark Manson, author of The Subtle Art of Not Giving A F*ck\r\n\r\n\'James Clear has spent years honing the art and studying the science of habits. This engaging, hands-on book is the guide you need to break bad routines and make good ones.\' Adam Grant, author of Originals\r\n\r\n\'Atomic Habits is a step-by-step manual for changing routines.\' Books of the Month, Financial Times\r\n\r\n\'A special book that will change how you approach your day and live your life.\' Ryan Holiday, author of The Obstacle is the Way', 362000, 'AtomicHabits.jpg'),
(9, '9786230060991', 'Jojo`s Bizarre Adventure ', 'Hirohiko Araki', 'Elex Media Komputindo', 'Abdul yang seharusnya sudah mati ternyata masih hidup!? Di sebuah pulau berlokasi dekat mesir, Polnareff diserang oleh stand “Judgement”. Yang menyelamatkan polnareff dari bahaya, tak diragukan lagi adalah Abdul. dengan tambahan Abdul yang menyelamatkan 1 nyawa dan 1 bantuan baru, Jotaro, dkk. pun berangkat menuju Mesir!\r\n\r\n*****\r\nDi antara jenis buku lainnya, komik memang disukai oleh semua kalangan mulai dari anak kecil hingga orang dewasa. Alasan komik lebih disukai oleh banyak orang karena disajikan dengan penuh dengan gambar dan cerita yang mengasyikan sehingga mampu menghilangkan rasa bosan di kala waktu senggang.\r\n\r\nKomik seringkali dijadikan sebagai koleksi dan diburu oleh penggemarnya karena serinya yang cukup terkenal dan kepopulerannya terus berlanjut sampai saat ini. Dalam memilih jenis komik, ada baiknya perhatikan terlebih dahulu ringkasan cerita komik di sampul bagian belakang sehingga sesuai dengan preferensi pribadi pembaca.\r\n\r\nProfil Penulis:\r\nHirohiko Araki\r\nLahir di kota Sendai, prefektur Miyagi pada 7 Juni 1960 Berzodiak gemini dan bergolongan darah B. Meraih juara kedua di Penghargaan Tezuka ke-20, mingguan Shonen Jump 1980, lewat karya \"Buso Poker\" (Poker Under Arms). Karya yang sama menjadi debutnya di edisi no. 1 majalah yang sama pada tahun 1981. Serial pertama adalah \"Mashonen B.T.\" (Cool Shock B.T.) di majalah edisi no. 42 tahun 1983, kemudian serial \'Bao Raihosha\" (Bach) sejak edisi no. 45 tahun 1984. \"Jojo\'s Bizarre Adventure\" yang serialnya dimulai sejak edisi gabungan no. 1 & 2 tahun 1987 mendapat dukungan yang luar biasa dari pembaca. Sekarang serial \"Jojo\'s Bizarre Adventure part 8: JoJolian\" tengah berlangsung di majalah Ultra Jump', 85000, 'jojo.jpg'),
(10, '9786230058103', 'Semua Bisa Menjadi Programmer Web PHP Basic', 'Ir. Yuniar Supardi', 'Elex Media Komputindo', 'Buku Semua Bisa Menjadi Programmer Web PHP Basic ini merupakan buku memandu Anda dalam belajar PHP dari dasar hingga program memakai database MySQL serta membuat web nilai. Bahasa skrip PHP merupakan bahasa skrip yang paling banyak komunitasnya di dunia, dengan belajar PHP Anda akan lebih mudah mencari skrip-skrip yang berhubungan dengan PHP di internet. Keunggulan buku ini memandu Anda membuat program web dengan PHP dari dasar hingga koneksi database populer, seperti MySQL, serta membuat web nilai dengan pembahasan yang mudah dan sistematik, sehingga Anda dengan mudah belajar dari buku ini.\r\n\r\nProfil Penulis:\r\nIr. Yuniar Supardi adalah seorang sarjana Teknik Informatika, lulusan tahun 1991. Beliau lahir di Kota Minyak Balikpapan, Kalimantan Timur. Mempunyai kegiatan utama sebagai penulis buku komputer nasional, Dosen Teknik Informatika dan Sistem Analis Komputer. Sudah lebih dari 60 judul buku komputer yang ditulis di PT Elex Media Komputindo (Kelompok Gramedia) dan best seller. Beberapa judul bukunya antara lain: Semua Bisa Menjadi Programmer Python Basic, Semua Bisa Menjadi Programmer Ruby Basic, Semua Bisa Menjadi Programmer Java Case Study, Semua Bisa Menjadi Programmer VB2012 Case Study, Semua Bisa Menjadi Programmer Android Case Study, dan masih menulis buku lainnya. Untuk konsultasi bisa ke email penulis: yuniarsupardi@gmail.com\r\n\r\nSelling Point:\r\n- Pembahasan mudah dan sistematis\r\n- Software pendukung disertakan', 95000, 'Semua Bisa Menjadi Programmer Web PHP Basic.jpg'),
(11, '9786230405310', 'The Maxwell Daily Reader', 'John C. Maxwell', 'Bhuana Ilmu Populer', 'Apa kunci menuju keberhasilan? Apa yang membedakan antara orang dengan banyak pencapaian dan orang dengan pencapaian ala kadarnya saja? Apa yang mereka kerjakan setiap hari? Rahasianya ada di dalam buku ini.\r\nThe Maxwell Daily Reader dirancang untuk membantu Anda meningkatkan diri setiap hari sepanjang tahun. Setiap halamannya memuat ringkasan dari salah satu buku Maxwell untuk menyemangati, mengajar, menantang, atau membantu Anda bertumbuh. Anda tidak akan dapat bertumbuh jika tidak mau berubah. Dan Anda tidak akan berubah, kecuali mengubah sesuatu dari apa yang Anda lakukan setiap hari. Buku ini akan mengajarkan Anda untuk memimpin, bukan hanya untuk diri sendiri, melainkan juga untuk orang-orang yang mengikuti Anda.\r\nJohn C. Maxwell adalah seorang pakar kepemimpinan, pembicara, dan penulis yang mendapatkan pengakuan internasional. Ia berhasil menjual lebih dari 13 juta bukunya. Beberapa bukunya yang laris manis: The 21 Irrefutable Laws of Leadership. Developing the Leader Within You, dan The 21 Indispensable Qualities of Leader. Organisasinya telah melatih lebih dari 2 juta orang pemimpin di seluruh dunia. Pendiri EQUIP and INJOY Stewardship Services, dan penulis buku terlaris versi New York Times, Wall Street Journal, dan Business Week ini dijuluki Guru Kepemimpinan Top Dunia oleh Leadershipgurus.net. Ia termasuk dalam 25 orang penulis dan seniman yang masuk 10th Anniversary Hall of Fame-nya Amazone.com.\r\nSegera miliki buku berjudul The Maxwell Daily Reader karya John C. Maxwell hanya di Toko Buku Gramedia terdekat atau melalui Gramedia.com.\r\nInformasi Lain :\r\nPenulis : John C. Maxwell\r\nPenerbit : Bhuana Ilmu Populer\r\nHalaman : 432\r\nISBN : 9786230405310\r\nUkuran : 16 cm x 23 cm\r\nBahasa : Indonesia\r\nTanggal Terbit : 8 Desember 2021', 86000, 'The Maxwell Daily Reader.jpg'),
(12, '9786022083795', 'Ayah, Ini Arahnya ke Mana, ya?', 'Khoirul Trian', 'Gradien Mediatama', 'Ayah, ternyata benar ya. Setelah dewasa kita semua harus punya banyak uang. Harus bekerja lebih keras lagi, harus bertarung dengan isi kepala sendiri. Harus menyampingkan banyak keinginan untuk sekadar tetap bertahan hidup sampai bertemu pagi lagi.\r\n\r\nAyah, setelah dewasa aku bertemu banyak orang yang menyakitkan dalam hidup dan kali ini aku gak punya banyak keberanian untuk melawannya. Ayah, kadang aku kalah, kadang aku kuat, kadang semuanya terjadi begitu saja dengan penuh pura-pura yang aku coba kesampingkan rasa sakitnya.\r\n\r\nAyah, hari ini aku kesepian dan gak tahu harus lari kemana lagi. Ayah, ini arahnya ke mana, ya? Anak kecil ini kehilangan jalan pulangnya.\r\n\r\nKeunggulan:\r\n- Secara garis besar, buku ini disusun sebagai bentuk rasa rindu seorang anak kepada sosok Ayah.\r\n- Mengangkat isu tentang fatherless yang sedang naik akhir-akhir ini.\r\n- Buku ini memiliki beberapa halaman activity sebagai bahan interaksi dengan pembaca, sehingga ketika membaca buku ini pembaca bisa mengerahkan perasaannya langsung.\r\n- Terdapat lima bab yang masing-masing memiliki daya tarik tersendiri dengan alur yang sudah terbentuk agar merangkul pembaca.\r\n- Buku ini akan sangat relate bagi sebagian besar kaum remaja, terutama yang tidak merasakan peran Ayah di hidupnya.\r\n\r\n\r\nDeskripsi Buku:\r\nAyah, Ini Arahnya ke Mana, ya? adalah buku yang mengangkat isu fatherless dan kehilangan. Buku ini hadir untuk kalian peluk dengan rasa rindu kepada seseorang yang sudah pergi. Mengisahkan seorang anak yang kehilangan sosok Ayah dan tidak tahu arah hidupnya akan ke mana. Ketika membaca buku ini kalian akan merasa bahwa ternyata hidup tanpa sebuah arahan dari seseorang yang sudah kita jadikan nahkoda memang sangat berat dan melelahkan. Namun, hidup harus tetap berjalan sebagaimana mestinya.\r\n\r\nMelalui buku ini, kalian juga akan menemukan eksperimen baru berupa interaksi yang menarik pada halaman aktivitas yang diberikan. Emosional pembaca akan diajak naik turun sampai pada titik ikhlas akan berjalannya hidup. Buku ini akan lebih mengajarkan kalian untuk bersyukur apabila sosok Ayah atau panutan kalian dalam hidup masih ada.', 80000, 'Ayah, Ini Arahnya ke Mana, ya.jpg'),
(14, '9786230057977', 'Sakamoto Days ', 'Yuto Suzuki', 'Elex Media Komputindo', 'Shin tengah di ujung tanduk, Sakamoto pun bergegas menolongnya lalu bentrok melawan Shinaya yang dikendalikan oleh Gaku! Amarah Sakamoto meledak karena teman-temannya dilukai! Bagaimana akhir dari ujian transfer JCC yang sarat kejadian tak terduga!? Bagaimana cara Sakamoto dan lainnya mengatasi gangguan X yang terus aktif di belakang layar dan berhasilkah mereka mendapatkan riwayat hidup X!?  Selling Point: *Ceritanya full action campur komedi. *Sampai Okt 22, sudah terjual 2 juta copies di Jepang. *Sudah diterjemahkan ke berbagai bahasa.  Di antara jenis buku lainnya, komik memang disukai oleh semua kalangan mulai dari anak kecil hingga orang dewasa. Alasan komik lebih disukai oleh banyak orang karena disajikan dengan penuh dengan gambar dan cerita yang mengasyikan sehingga mampu menghilangkan rasa bosan di kala waktu senggang.  Komik seringkali dijadikan sebagai koleksi dan diburu oleh penggemarnya karena serinya yang cukup terkenal dan kepopulerannya terus berlanjut sampai saat ini. Dalam memilih jenis kom', 40000, 'sakamotodays.jpg'),
(15, '9786024246945', 'Laut Bercerita Rp92.000', 'Leila S. Chudori', 'Kepustakaan Populer Gramedia', 'Buku ini terdiri atas dua bagian. Bagian pertama mengambil sudut pandang seorang mahasiswa aktivis bernama Laut, menceritakan bagaimana Laut dan kawan-kawannya menyusun rencana, berpindah-pindah dalam pelarian, hingga tertangkap oleh pasukan rahasia. Sedangkan bagian kedua dikisahkan oleh Asmara, adik Laut. Bagian kedua mewakili perasaan keluarga korban penghilangan paksa, bagaimana pencarian mereka terhadap kerabat mereka yang tak pernah kembali. Buku ini ditulis sebagai bentuk tribute bagi para aktivis yang diculik, yang kembali, dan yang tak kembali dan keluarga yang terus menerus sampai sekarang mencari-cari jawaban.  Novel ini merupakan perwujudan dalam bentuk fiksi bahwa kita sebagai bangsa Indonesia tidak boleh melupakan sejarah yang telah membentuk sekaligus menjadi tumpuan bangsa Ini. Novel ini juga mengajak pembaca menguak misteri-misteri bangsa ini yang mana tidak diajarkan di sekolah. Walaupun novel ini adalah fiksi, laut bercerita menunjukkan kepada pembaca bahwa negeri ini pernah memasuki masa pemerintahan yang kelam.', 92000, '9786024246945_Laut-Bercerita.jpg');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `buku`
--
ALTER TABLE `buku`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `buku`
--
ALTER TABLE `buku`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
